version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    build: .

    ports:
      - "5678:5678"   # Timeweb автоматически проксирует первый опубликованный порт

    environment:
      # --- базовые настройки ---
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Europe/Moscow
      - TZ=Europe/Moscow

      # --- авторизация для доступа в интерфейс n8n ---
      - N8N_BASIC_AUTH_ACTIVE=true

      # --- включаем возможность использовать внешние модули в Function-ноды ---
      - NODE_FUNCTION_ALLOW_EXTERNAL=*

      # --- путь к сохранению данных ---
      - N8N_USER_FOLDER=/home/node/.n8n

      # --- если хочешь использовать домен (см. ниже) ---
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=${WEBHOOK_URL}
      - N8N_PUSH_BACKEND=sse
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - N8N_PROXY_HOPS=1

      # если Origin всё равно чудит — временно отключить проверку
      # (можно закомментировать, попробовать без него, и включить только если ошибка остаётся)
      - N8N_DISABLE_PUSH_ORIGIN_CHECK=true
